name: Mise à jour automatique du Jardin

on:
  repository_dispatch:
    types: [sheet_updated]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code du site
        uses: actions/checkout@v4  # 👈 Mis à jour ici en v4

      - name: Téléchargement des données depuis Google Sheets
        run: |
          curl -L "https://script.google.com/macros/s/AKfycbxxToz22V88elCCjxLqjRtsb5iBIC156cbBFRIlTsju2SwOj9yNnKqzAwFITXMg_wij/exec" -o annonces.json

      - name: Mise à jour du fichier sur le site
        run: |
          git config --global user.name 'Robot-Jardinier'
          git config --global user.email 'robot@jardin.com'
          git add annonces.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "🌱 Maj auto des annonces" && git push)
